/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.ControlActividad3;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author juare
 */
public class Actividad_3 extends javax.swing.JFrame {

    /**
     * Creates new form RelacionarPalabras
     */
    
    ControlActividad3 control;
  
    public Actividad_3() {
        initComponents();
        this.setLocationRelativeTo(null);
        control = new ControlActividad3(this);   
    }

    public JButton getjButton_cambiar() {
        return jButton_cambiar;
    }

    public JButton getjButton_verificar() {
        return jButton_verificar;
    }

    
    public JButton getjButton1_Salir() {
        return jButton1_Salir;
    }
    
    public JPanel getjPanel3_fondo() {
        return jPanel3_fondo;
    }

    public void setjPanel3_fondo(JPanel jPanel3_fondo) {
        this.jPanel3_fondo = jPanel3_fondo;
    }
    

    public JLabel getjLabel_destino1() {
        return jLabel_destino1;
    }

    public void setjLabel_destino1(JLabel jLabel_destino1) {
        this.jLabel_destino1 = jLabel_destino1;
    }

    public JLabel getjLabel_destino2() {
        return jLabel_destino2;
    }

    public void setjLabel_destino2(JLabel jLabel_destino2) {
        this.jLabel_destino2 = jLabel_destino2;
    }

    public JLabel getjLabel_destino3() {
        return jLabel_destino3;
    }

    public void setjLabel_destino3(JLabel jLabel_destino3) {
        this.jLabel_destino3 = jLabel_destino3;
    }
    
    public JLabel getjLabel1_palabra1() {
        return jLabel1_palabra1;
    }

    public void setjLabel1_palabra1(JLabel jLabel1_palabra1) {
        this.jLabel1_palabra1 = jLabel1_palabra1;
    }

    public JLabel getjLabel2_palabra3() {
        return jLabel2_palabra3;
    }

    public void setjLabel2_palabra3(JLabel jLabel2_palabra3) {
        this.jLabel2_palabra3 = jLabel2_palabra3;
    }

    public JLabel getjLabel3_palabra2() {
        return jLabel3_palabra2;
    }

    public void setjLabel3_palabra2(JLabel jLabel3_palabra2) {
        this.jLabel3_palabra2 = jLabel3_palabra2;
    }

    public JLabel getJlabel_image1() {
        return jlabel_image1;
    }

    public void setJlabel_image1(JLabel jlabel_image1) {
        this.jlabel_image1 = jlabel_image1;
    }

    public JLabel getJlabel_image2() {
        return jlabel_image2;
    }

    public void setJlabel_image2(JLabel jlabel_image2) {
        this.jlabel_image2 = jlabel_image2;
    }

    public JLabel getJlabel_image3() {
        return jlabel_image3;
    }

    public void setJlabel_image3(JLabel jlabel_image3) {
        this.jlabel_image3 = jlabel_image3;
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3_fondo = new javax.swing.JPanel();
        jlabel_image2 = new javax.swing.JLabel();
        jlabel_image3 = new javax.swing.JLabel();
        jlabel_image1 = new javax.swing.JLabel();
        jLabel1_palabra1 = new javax.swing.JLabel();
        jLabel2_palabra3 = new javax.swing.JLabel();
        jLabel3_palabra2 = new javax.swing.JLabel();
        jLabel_destino1 = new javax.swing.JLabel();
        jLabel_destino2 = new javax.swing.JLabel();
        jLabel_destino3 = new javax.swing.JLabel();
        jButton1_Salir = new javax.swing.JButton();
        jButton_verificar = new javax.swing.JButton();
        jButton_cambiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3_fondo.setBackground(new java.awt.Color(118, 187, 215));
        jPanel3_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel_image2.setBackground(new java.awt.Color(255, 255, 255));
        jlabel_image2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3_fondo.add(jlabel_image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 170, 160));

        jlabel_image3.setBackground(new java.awt.Color(255, 255, 255));
        jlabel_image3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3_fondo.add(jlabel_image3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 170, 160));

        jlabel_image1.setBackground(new java.awt.Color(255, 255, 255));
        jlabel_image1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3_fondo.add(jlabel_image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 170, 160));

        jLabel1_palabra1.setBackground(new java.awt.Color(217, 217, 217));
        jLabel1_palabra1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1_palabra1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1_palabra1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_palabra1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1_palabra1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_palabra1.setOpaque(true);
        jPanel3_fondo.add(jLabel1_palabra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 235, 100));

        jLabel2_palabra3.setBackground(new java.awt.Color(217, 217, 217));
        jLabel2_palabra3.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel2_palabra3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2_palabra3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_palabra3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2_palabra3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2_palabra3.setOpaque(true);
        jPanel3_fondo.add(jLabel2_palabra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 235, 100));

        jLabel3_palabra2.setBackground(new java.awt.Color(217, 217, 217));
        jLabel3_palabra2.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel3_palabra2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3_palabra2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3_palabra2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3_palabra2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3_palabra2.setOpaque(true);
        jPanel3_fondo.add(jLabel3_palabra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 235, 100));

        jLabel_destino1.setBackground(new java.awt.Color(217, 217, 217));
        jLabel_destino1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jLabel_destino1.setName("2"); // NOI18N
        jLabel_destino1.setOpaque(true);
        jPanel3_fondo.add(jLabel_destino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 235, 100));

        jLabel_destino2.setBackground(new java.awt.Color(217, 217, 217));
        jLabel_destino2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(153, 153, 153)));
        jLabel_destino2.setName("1"); // NOI18N
        jLabel_destino2.setOpaque(true);
        jPanel3_fondo.add(jLabel_destino2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 235, 100));

        jLabel_destino3.setBackground(new java.awt.Color(217, 217, 217));
        jLabel_destino3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(102, 102, 102)));
        jLabel_destino3.setName("3"); // NOI18N
        jLabel_destino3.setOpaque(true);
        jPanel3_fondo.add(jLabel_destino3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 235, 100));

        jButton1_Salir.setBackground(new java.awt.Color(51, 51, 255));
        jButton1_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/salirrr.png"))); // NOI18N
        jButton1_Salir.setBorderPainted(false);
        jButton1_Salir.setContentAreaFilled(false);
        jButton1_Salir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Frame 106.png"))); // NOI18N
        jButton1_Salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Frame 104.png"))); // NOI18N
        jPanel3_fondo.add(jButton1_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, 100, 70));

        jButton_verificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Verificar1.png"))); // NOI18N
        jButton_verificar.setBorderPainted(false);
        jButton_verificar.setContentAreaFilled(false);
        jButton_verificar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Verificar3.png"))); // NOI18N
        jButton_verificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Verificar2.png"))); // NOI18N
        jPanel3_fondo.add(jButton_verificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 200, -1, -1));

        jButton_cambiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Cambiar1.png"))); // NOI18N
        jButton_cambiar.setBorderPainted(false);
        jButton_cambiar.setContentAreaFilled(false);
        jButton_cambiar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Cambiar3.png"))); // NOI18N
        jButton_cambiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Cambiar2.png"))); // NOI18N
        jPanel3_fondo.add(jButton_cambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 310, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Relaciona la palabra ");
        jPanel3_fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actividad_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actividad_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actividad_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actividad_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actividad_3().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Salir;
    private javax.swing.JButton jButton_cambiar;
    private javax.swing.JButton jButton_verificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_palabra1;
    private javax.swing.JLabel jLabel2_palabra3;
    private javax.swing.JLabel jLabel3_palabra2;
    private javax.swing.JLabel jLabel_destino1;
    private javax.swing.JLabel jLabel_destino2;
    private javax.swing.JLabel jLabel_destino3;
    private javax.swing.JPanel jPanel3_fondo;
    private javax.swing.JLabel jlabel_image1;
    private javax.swing.JLabel jlabel_image2;
    private javax.swing.JLabel jlabel_image3;
    // End of variables declaration//GEN-END:variables
}
