/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;


import com.formdev.flatlaf.FlatLightLaf;
import controlador.ControlActividad2;
import controlador.ControlActividad4;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author almen
 */
public class Actividad_4 extends javax.swing.JFrame {
    ControlActividad4 objControladorActividad4;
   
    /**
     * Creates new form CompletarPalabras
     */
   ControlActividad2 objControl5;
    public Actividad_4() {
        initComponents();
       
        objControladorActividad4 = new ControlActividad4(this);
        this.setLocationRelativeTo(null);
    }
    
    public JButton getjButton1_Salir_act_5() {
        return jButton1_Salir_act_5;
    }

    public JButton getjButton1_audio_palabra() {
        return jButton1_audio_palabra;
    }

    public JLabel getjLabel_word1() {
        return jLabel_word1;
    }

    public JLabel getjLabel_word2() {
        return jLabel_word2;
    }

    public JLabel getjLabel_word3() {
        return jLabel_word3;
    }

    public JButton getjButton1_Cambiar_audio_palabra() {
        return jButton1_Cambiar_audio_palabra;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1_Salir_act_5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel_word1 = new javax.swing.JLabel();
        jLabel_word2 = new javax.swing.JLabel();
        jLabel_word3 = new javax.swing.JLabel();
        jButton1_audio_palabra = new javax.swing.JButton();
        jButton1_Cambiar_audio_palabra = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 690));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1_Salir_act_5.setBackground(new java.awt.Color(153, 51, 255));
        jButton1_Salir_act_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/salirrr.png"))); // NOI18N
        jButton1_Salir_act_5.setBorderPainted(false);
        jButton1_Salir_act_5.setContentAreaFilled(false);
        jButton1_Salir_act_5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1_Salir_act_5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Frame 106.png"))); // NOI18N
        jButton1_Salir_act_5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Frame 104.png"))); // NOI18N
        jPanel1.add(jButton1_Salir_act_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Selecciona lo que escuchas");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 620, 30));

        jLabel_word1.setBackground(new java.awt.Color(102, 51, 255));
        jLabel_word1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel_word1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_word1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_word1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel_word1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 210, 70));

        jLabel_word2.setBackground(new java.awt.Color(102, 51, 255));
        jLabel_word2.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel_word2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_word2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_word2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel_word2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 210, 70));

        jLabel_word3.setBackground(new java.awt.Color(102, 51, 255));
        jLabel_word3.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel_word3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_word3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_word3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel_word3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, 220, 70));

        jButton1_audio_palabra.setBackground(new java.awt.Color(153, 153, 255));
        jButton1_audio_palabra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/sistemas-de-escucha-asistida.png"))); // NOI18N
        jButton1_audio_palabra.setBorderPainted(false);
        jButton1_audio_palabra.setContentAreaFilled(false);
        jPanel1.add(jButton1_audio_palabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 140, 120));

        jButton1_Cambiar_audio_palabra.setBackground(new java.awt.Color(51, 51, 255));
        jButton1_Cambiar_audio_palabra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Cambiar1.png"))); // NOI18N
        jButton1_Cambiar_audio_palabra.setText("Cambiar Palabra");
        jButton1_Cambiar_audio_palabra.setBorderPainted(false);
        jButton1_Cambiar_audio_palabra.setContentAreaFilled(false);
        jButton1_Cambiar_audio_palabra.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Cambiar3.png"))); // NOI18N
        jButton1_Cambiar_audio_palabra.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Cambiar2.png"))); // NOI18N
        jPanel1.add(jButton1_Cambiar_audio_palabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 210, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/op.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/op.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/op.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/fondoo.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1220, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actividad_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Cambiar_audio_palabra;
    private javax.swing.JButton jButton1_Salir_act_5;
    private javax.swing.JButton jButton1_audio_palabra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_word1;
    private javax.swing.JLabel jLabel_word2;
    private javax.swing.JLabel jLabel_word3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
