/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.ControlActividad1;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author juare
 */
public class Actividad_1 extends javax.swing.JFrame {

    /**
     * Creates new form Actividad_1
     */
    ControlActividad1 objcontrolActi;
    
    public Actividad_1() {
       
        initComponents();
        objcontrolActi= new ControlActividad1(this);
        this.setLocationRelativeTo(null);
    }

    public JButton getjButton10_J() {
        return jButton10_J;
    }

    public JButton getjButton11_K() {
        return jButton11_K;
    }

    public JButton getjButton12_L() {
        return jButton12_L;
    }

    public JButton getjButton13_M() {
        return jButton13_M;
    }

    public JButton getjButton14_N() {
        return jButton14_N;
    }

    public JButton getjButton15_Ñ() {
        return jButton15_Ñ;
    }

    public JButton getjButton16_O() {
        return jButton16_O;
    }

    public JButton getjButton17_P() {
        return jButton17_P;
    }

    public JButton getjButton18_Q() {
        return jButton18_Q;
    }

    public JButton getjButton19_R() {
        return jButton19_R;
    }

    public JButton getjButton1_Z() {
        return jButton1_Z;
    }

    public JButton getjButton20_S() {
        return jButton20_S;
    }

    public JButton getjButton21_T() {
        return jButton21_T;
    }

    public JButton getjButton22_U() {
        return jButton22_U;
    }

    public JButton getjButton23_X() {
        return jButton23_X;
    }

    public JButton getjButton24_Y() {
        return jButton24_Y;
    }

    public JButton getjButton25_V() {
        return jButton25_V;
    }

    public JButton getjButton26_W() {
        return jButton26_W;
    }

    public JButton getjButton4_D() {
        return jButton4_D;
    }

    public JButton getjButton5_E() {
        return jButton5_E;
    }

    public JButton getjButton6_F() {
        return jButton6_F;
    }

    public JButton getjButton7_G() {
        return jButton7_G;
    }

    public JButton getjButton8_H() {
        return jButton8_H;
    }

    public JButton getjButton9_I() {
        return jButton9_I;
    }

    public JButton getjButton_A() {
        return jButton_A;
    }

    public JButton getjButton_B() {
        return jButton_B;
    }

    public JButton getjButton_C() {
        return jButton_C;
    }

    public JButton getjButton1_Salir_act_1() {
        return jButton1_Salir_act_1;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Actividad_1 = new javax.swing.JPanel();
        jButton_A = new javax.swing.JButton();
        jButton_B = new javax.swing.JButton();
        jButton_C = new javax.swing.JButton();
        jButton4_D = new javax.swing.JButton();
        jButton5_E = new javax.swing.JButton();
        jButton6_F = new javax.swing.JButton();
        jButton7_G = new javax.swing.JButton();
        jButton8_H = new javax.swing.JButton();
        jButton9_I = new javax.swing.JButton();
        jButton10_J = new javax.swing.JButton();
        jButton11_K = new javax.swing.JButton();
        jButton12_L = new javax.swing.JButton();
        jButton13_M = new javax.swing.JButton();
        jButton14_N = new javax.swing.JButton();
        jButton15_Ñ = new javax.swing.JButton();
        jButton16_O = new javax.swing.JButton();
        jButton17_P = new javax.swing.JButton();
        jButton18_Q = new javax.swing.JButton();
        jButton19_R = new javax.swing.JButton();
        jButton20_S = new javax.swing.JButton();
        jButton21_T = new javax.swing.JButton();
        jButton22_U = new javax.swing.JButton();
        jButton23_X = new javax.swing.JButton();
        jButton24_Y = new javax.swing.JButton();
        jButton25_V = new javax.swing.JButton();
        jButton26_W = new javax.swing.JButton();
        jButton1_Z = new javax.swing.JButton();
        jButton1_Salir_act_1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Actividad_1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Actividad_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_A.setBackground(new java.awt.Color(51, 153, 0));
        jButton_A.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 36)); // NOI18N
        jButton_A.setForeground(new java.awt.Color(255, 255, 255));
        jButton_A.setText("A");
        jButton_A.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 80, 80));

        jButton_B.setBackground(new java.awt.Color(102, 0, 102));
        jButton_B.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 36)); // NOI18N
        jButton_B.setForeground(new java.awt.Color(255, 255, 255));
        jButton_B.setText("B");
        jButton_B.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 80, 80));

        jButton_C.setBackground(new java.awt.Color(204, 204, 0));
        jButton_C.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton_C.setForeground(new java.awt.Color(255, 255, 255));
        jButton_C.setText("C");
        jButton_C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 80, 80));

        jButton4_D.setBackground(new java.awt.Color(0, 0, 255));
        jButton4_D.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        jButton4_D.setForeground(new java.awt.Color(255, 255, 255));
        jButton4_D.setText("D");
        jButton4_D.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton4_D, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 80, 80));

        jButton5_E.setBackground(new java.awt.Color(255, 51, 51));
        jButton5_E.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton5_E.setForeground(new java.awt.Color(255, 255, 255));
        jButton5_E.setText("E");
        jButton5_E.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton5_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 80, 80));

        jButton6_F.setBackground(new java.awt.Color(255, 153, 153));
        jButton6_F.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 36)); // NOI18N
        jButton6_F.setForeground(new java.awt.Color(255, 255, 255));
        jButton6_F.setText("F");
        jButton6_F.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton6_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, 80, 80));

        jButton7_G.setBackground(new java.awt.Color(0, 204, 51));
        jButton7_G.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton7_G.setForeground(new java.awt.Color(255, 255, 255));
        jButton7_G.setText("G");
        jButton7_G.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton7_G, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, 80, 80));

        jButton8_H.setBackground(new java.awt.Color(255, 102, 102));
        jButton8_H.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton8_H.setForeground(new java.awt.Color(255, 255, 255));
        jButton8_H.setText("H");
        jButton8_H.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton8_H, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 80, 80));

        jButton9_I.setBackground(new java.awt.Color(51, 51, 255));
        jButton9_I.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton9_I.setForeground(new java.awt.Color(255, 255, 255));
        jButton9_I.setText("I");
        jButton9_I.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton9_I, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 80, 80));

        jButton10_J.setBackground(new java.awt.Color(51, 0, 153));
        jButton10_J.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton10_J.setForeground(new java.awt.Color(255, 255, 255));
        jButton10_J.setText("J");
        jButton10_J.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton10_J, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 80, 80));

        jButton11_K.setBackground(new java.awt.Color(255, 102, 102));
        jButton11_K.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton11_K.setForeground(new java.awt.Color(255, 255, 255));
        jButton11_K.setText("K");
        jButton11_K.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton11_K, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 80, 80));

        jButton12_L.setBackground(new java.awt.Color(51, 102, 255));
        jButton12_L.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton12_L.setForeground(new java.awt.Color(255, 255, 255));
        jButton12_L.setText("L");
        jButton12_L.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton12_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 80, 80));

        jButton13_M.setBackground(new java.awt.Color(255, 51, 255));
        jButton13_M.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton13_M.setForeground(new java.awt.Color(255, 255, 255));
        jButton13_M.setText("M");
        jButton13_M.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton13_M, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 80, 80));

        jButton14_N.setBackground(new java.awt.Color(0, 153, 153));
        jButton14_N.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton14_N.setForeground(new java.awt.Color(255, 255, 255));
        jButton14_N.setText("N");
        jButton14_N.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton14_N, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, 80, 80));

        jButton15_Ñ.setBackground(new java.awt.Color(204, 102, 0));
        jButton15_Ñ.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton15_Ñ.setForeground(new java.awt.Color(255, 255, 255));
        jButton15_Ñ.setText("Ñ");
        jButton15_Ñ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton15_Ñ, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 80, 80));

        jButton16_O.setBackground(new java.awt.Color(255, 153, 153));
        jButton16_O.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton16_O.setForeground(new java.awt.Color(255, 255, 255));
        jButton16_O.setText("O");
        jButton16_O.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton16_O, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 80, 80));

        jButton17_P.setBackground(new java.awt.Color(204, 0, 153));
        jButton17_P.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton17_P.setForeground(new java.awt.Color(255, 255, 255));
        jButton17_P.setText("P");
        jButton17_P.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton17_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 80, 80));

        jButton18_Q.setBackground(new java.awt.Color(153, 153, 153));
        jButton18_Q.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton18_Q.setForeground(new java.awt.Color(255, 255, 255));
        jButton18_Q.setText("Q");
        jButton18_Q.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton18_Q, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 80, 80));

        jButton19_R.setBackground(new java.awt.Color(255, 153, 0));
        jButton19_R.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton19_R.setForeground(new java.awt.Color(255, 255, 255));
        jButton19_R.setText("R");
        jButton19_R.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton19_R, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 80, 80));

        jButton20_S.setBackground(new java.awt.Color(0, 153, 51));
        jButton20_S.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton20_S.setForeground(new java.awt.Color(255, 255, 255));
        jButton20_S.setText("S");
        jButton20_S.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton20_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 80, 80));

        jButton21_T.setBackground(new java.awt.Color(255, 102, 0));
        jButton21_T.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton21_T.setForeground(new java.awt.Color(255, 255, 255));
        jButton21_T.setText("T");
        jButton21_T.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton21_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 260, 80, 80));

        jButton22_U.setBackground(new java.awt.Color(0, 102, 51));
        jButton22_U.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton22_U.setForeground(new java.awt.Color(255, 255, 255));
        jButton22_U.setText("U");
        jButton22_U.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton22_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 80, 80));

        jButton23_X.setBackground(new java.awt.Color(0, 255, 0));
        jButton23_X.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton23_X.setForeground(new java.awt.Color(255, 255, 255));
        jButton23_X.setText("X");
        jButton23_X.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton23_X, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 80, 80));

        jButton24_Y.setBackground(new java.awt.Color(204, 204, 0));
        jButton24_Y.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton24_Y.setForeground(new java.awt.Color(255, 255, 255));
        jButton24_Y.setText("Y");
        jButton24_Y.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton24_Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 80, 80));

        jButton25_V.setBackground(new java.awt.Color(255, 102, 255));
        jButton25_V.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton25_V.setForeground(new java.awt.Color(255, 255, 255));
        jButton25_V.setText("V");
        jButton25_V.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton25_V, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 80, 80));

        jButton26_W.setBackground(new java.awt.Color(0, 153, 153));
        jButton26_W.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton26_W.setForeground(new java.awt.Color(255, 255, 255));
        jButton26_W.setText("W");
        jButton26_W.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton26_W, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 80, 80));

        jButton1_Z.setBackground(new java.awt.Color(255, 204, 51));
        jButton1_Z.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jButton1_Z.setText("Z");
        jButton1_Z.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Actividad_1.add(jButton1_Z, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 80, 80));

        jButton1_Salir_act_1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1_Salir_act_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton.salir.png"))); // NOI18N
        jButton1_Salir_act_1.setBorder(null);
        jButton1_Salir_act_1.setBorderPainted(false);
        jButton1_Salir_act_1.setOpaque(true);
        jPanel_Actividad_1.add(jButton1_Salir_act_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 60));

        getContentPane().add(jPanel_Actividad_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actividad_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actividad_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actividad_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actividad_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actividad_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10_J;
    private javax.swing.JButton jButton11_K;
    private javax.swing.JButton jButton12_L;
    private javax.swing.JButton jButton13_M;
    private javax.swing.JButton jButton14_N;
    private javax.swing.JButton jButton15_Ñ;
    private javax.swing.JButton jButton16_O;
    private javax.swing.JButton jButton17_P;
    private javax.swing.JButton jButton18_Q;
    private javax.swing.JButton jButton19_R;
    private javax.swing.JButton jButton1_Salir_act_1;
    private javax.swing.JButton jButton1_Z;
    private javax.swing.JButton jButton20_S;
    private javax.swing.JButton jButton21_T;
    private javax.swing.JButton jButton22_U;
    private javax.swing.JButton jButton23_X;
    private javax.swing.JButton jButton24_Y;
    private javax.swing.JButton jButton25_V;
    private javax.swing.JButton jButton26_W;
    private javax.swing.JButton jButton4_D;
    private javax.swing.JButton jButton5_E;
    private javax.swing.JButton jButton6_F;
    private javax.swing.JButton jButton7_G;
    private javax.swing.JButton jButton8_H;
    private javax.swing.JButton jButton9_I;
    private javax.swing.JButton jButton_A;
    private javax.swing.JButton jButton_B;
    private javax.swing.JButton jButton_C;
    private javax.swing.JPanel jPanel_Actividad_1;
    // End of variables declaration//GEN-END:variables
    
}
