/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.ControlActividad3;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author juare
 */
public class Actividad_3 extends javax.swing.JFrame {

    /**
     * Creates new form RelacionarPalabras
     */
    
    ControlActividad3 control;
    public Actividad_3() {
        initComponents();
        this.setLocationRelativeTo(null);
        control = new ControlActividad3(this);

        
    }

    public JButton getjButton1_Salir() {
        return jButton1_Salir;
    }
    
    public JPanel getjPanel3_fondo() {
        return jPanel3_fondo;
    }

    public void setjPanel3_fondo(JPanel jPanel3_fondo) {
        this.jPanel3_fondo = jPanel3_fondo;
    }
    

    public JLabel getjLabel_destino1() {
        return jLabel_destino1;
    }

    public void setjLabel_destino1(JLabel jLabel_destino1) {
        this.jLabel_destino1 = jLabel_destino1;
    }

    public JLabel getjLabel_destino2() {
        return jLabel_destino2;
    }

    public void setjLabel_destino2(JLabel jLabel_destino2) {
        this.jLabel_destino2 = jLabel_destino2;
    }

    public JLabel getjLabel_destino3() {
        return jLabel_destino3;
    }

    public void setjLabel_destino3(JLabel jLabel_destino3) {
        this.jLabel_destino3 = jLabel_destino3;
    }
    
    public JLabel getjLabel1_palabra1() {
        return jLabel1_palabra1;
    }

    public void setjLabel1_palabra1(JLabel jLabel1_palabra1) {
        this.jLabel1_palabra1 = jLabel1_palabra1;
    }

    public JLabel getjLabel2_palabra3() {
        return jLabel2_palabra3;
    }

    public void setjLabel2_palabra3(JLabel jLabel2_palabra3) {
        this.jLabel2_palabra3 = jLabel2_palabra3;
    }

    public JLabel getjLabel3_palabra2() {
        return jLabel3_palabra2;
    }

    public void setjLabel3_palabra2(JLabel jLabel3_palabra2) {
        this.jLabel3_palabra2 = jLabel3_palabra2;
    }

    public JLabel getJlabel_image1() {
        return jlabel_image1;
    }

    public void setJlabel_image1(JLabel jlabel_image1) {
        this.jlabel_image1 = jlabel_image1;
    }

    public JLabel getJlabel_image2() {
        return jlabel_image2;
    }

    public void setJlabel_image2(JLabel jlabel_image2) {
        this.jlabel_image2 = jlabel_image2;
    }

    public JLabel getJlabel_image3() {
        return jlabel_image3;
    }

    public void setJlabel_image3(JLabel jlabel_image3) {
        this.jlabel_image3 = jlabel_image3;
    }
   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3_fondo = new javax.swing.JPanel();
        jlabel_image1 = new javax.swing.JLabel();
        jlabel_image2 = new javax.swing.JLabel();
        jlabel_image3 = new javax.swing.JLabel();
        jLabel1_palabra1 = new javax.swing.JLabel();
        jLabel2_palabra3 = new javax.swing.JLabel();
        jLabel3_palabra2 = new javax.swing.JLabel();
        jLabel_destino1 = new javax.swing.JLabel();
        jLabel_destino2 = new javax.swing.JLabel();
        jLabel_destino3 = new javax.swing.JLabel();
        jButton1_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3_fondo.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel_image1.setBackground(new java.awt.Color(204, 204, 204));
        jlabel_image1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3_fondo.add(jlabel_image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 130, 110));

        jlabel_image2.setBackground(new java.awt.Color(204, 204, 204));
        jlabel_image2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3_fondo.add(jlabel_image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 130, 110));

        jlabel_image3.setBackground(new java.awt.Color(204, 204, 204));
        jlabel_image3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3_fondo.add(jlabel_image3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 130, 110));

        jLabel1_palabra1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1_palabra1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1_palabra1.setText("brian");
        jLabel1_palabra1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1_palabra1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_palabra1.setOpaque(true);
        jPanel3_fondo.add(jLabel1_palabra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 120, 200, 70));

        jLabel2_palabra3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2_palabra3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3_fondo.add(jLabel2_palabra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 400, 200, 60));

        jLabel3_palabra2.setText("b");
        jLabel3_palabra2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3_palabra2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3_palabra2.setOpaque(true);
        jPanel3_fondo.add(jLabel3_palabra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 250, 200, 70));

        jLabel_destino1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_destino1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel_destino1.setOpaque(true);
        jPanel3_fondo.add(jLabel_destino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 260, 90));

        jLabel_destino2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_destino2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel_destino2.setOpaque(true);
        jPanel3_fondo.add(jLabel_destino2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 260, 90));

        jLabel_destino3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_destino3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel_destino3.setOpaque(true);
        jPanel3_fondo.add(jLabel_destino3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 250, 80));

        jButton1_Salir.setBackground(new java.awt.Color(51, 51, 255));
        jButton1_Salir.setText("SALIR");
        jPanel3_fondo.add(jButton1_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actividad_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actividad_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actividad_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actividad_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actividad_3().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Salir;
    private javax.swing.JLabel jLabel1_palabra1;
    private javax.swing.JLabel jLabel2_palabra3;
    private javax.swing.JLabel jLabel3_palabra2;
    private javax.swing.JLabel jLabel_destino1;
    private javax.swing.JLabel jLabel_destino2;
    private javax.swing.JLabel jLabel_destino3;
    private javax.swing.JPanel jPanel3_fondo;
    private javax.swing.JLabel jlabel_image1;
    private javax.swing.JLabel jlabel_image2;
    private javax.swing.JLabel jlabel_image3;
    // End of variables declaration//GEN-END:variables
}
