/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;


import com.formdev.flatlaf.FlatLightLaf;
import controlador.ControlActividad2;
import controlador.ControlActividad5;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author almen
 */
public class Actividad_5 extends javax.swing.JFrame {
    ControlActividad5 objControladorActividad5;
   
    /**
     * Creates new form CompletarPalabras
     */
   ControlActividad2 objControl5;
    public Actividad_5() {
        initComponents();
       
        objControladorActividad5 = new ControlActividad5(this);
        this.setLocationRelativeTo(null);
    }

    public JButton getjButton1_Vericicar_oracion() {
        return jButton1_Vericicar_oracion;
    }
    

    public JButton getjButton1_Cambiar_oracion() {
        return jButton1_Cambiar_oracion;
    }

    public JButton getjButton1_Salir_act_5() {
        return jButton1_Salir_act_5;
    }

    public JButton getjButton1_Uno() {
        return jButton1_Uno;
    }

    public JButton getjButton3_Dos() {
        return jButton3_Dos;
    }

    public JButton getjButton3_Tres() {
        return jButton3_Tres;
    }

    public JLabel getjLabel3_oracion() {
        return jLabel3_oracion;
    }

    public JLabel getjLabel_opcionUno() {
        return jLabel_opcionUno;
    }

    public JLabel getjLabel_palabraOpcionDos() {
        return jLabel_palabraOpcionDos;
    }

    public JLabel getjLabel_palabraOpcionTres() {
        return jLabel_palabraOpcionTres;
    }


  


    public JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1_Salir_act_5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1_Vericicar_oracion = new javax.swing.JButton();
        jLabel_opcionUno = new javax.swing.JLabel();
        jLabel_palabraOpcionDos = new javax.swing.JLabel();
        jLabel_palabraOpcionTres = new javax.swing.JLabel();
        jButton1_Cambiar_oracion = new javax.swing.JButton();
        jButton1_Uno = new javax.swing.JButton();
        jButton3_Dos = new javax.swing.JButton();
        jButton3_Tres = new javax.swing.JButton();
        jLabel3_oracion = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setFont(new java.awt.Font("Arial Narrow", 3, 24)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 690));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1_Salir_act_5.setBackground(new java.awt.Color(153, 51, 255));
        jButton1_Salir_act_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/salirrr.png"))); // NOI18N
        jButton1_Salir_act_5.setBorderPainted(false);
        jButton1_Salir_act_5.setContentAreaFilled(false);
        jButton1_Salir_act_5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1_Salir_act_5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Frame 106.png"))); // NOI18N
        jButton1_Salir_act_5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Frame 104.png"))); // NOI18N
        jPanel1.add(jButton1_Salir_act_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Selecciona lo que escuchas");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 620, 30));

        jButton1_Vericicar_oracion.setBackground(new java.awt.Color(51, 51, 255));
        jButton1_Vericicar_oracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Verificar1.png"))); // NOI18N
        jButton1_Vericicar_oracion.setText("Verificar");
        jButton1_Vericicar_oracion.setBorderPainted(false);
        jButton1_Vericicar_oracion.setContentAreaFilled(false);
        jButton1_Vericicar_oracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_Vericicar_oracion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Verificar3.png"))); // NOI18N
        jButton1_Vericicar_oracion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Verificar2.png"))); // NOI18N
        jPanel1.add(jButton1_Vericicar_oracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 210, 90));

        jLabel_opcionUno.setBackground(new java.awt.Color(102, 51, 255));
        jLabel_opcionUno.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel_opcionUno.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_opcionUno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_opcionUno.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 255)));
        jLabel_opcionUno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_opcionUno.setOpaque(true);
        jPanel1.add(jLabel_opcionUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 210, 70));

        jLabel_palabraOpcionDos.setBackground(new java.awt.Color(102, 51, 255));
        jLabel_palabraOpcionDos.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel_palabraOpcionDos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_palabraOpcionDos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_palabraOpcionDos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel_palabraOpcionDos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_palabraOpcionDos.setOpaque(true);
        jPanel1.add(jLabel_palabraOpcionDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 210, 70));

        jLabel_palabraOpcionTres.setBackground(new java.awt.Color(102, 51, 255));
        jLabel_palabraOpcionTres.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel_palabraOpcionTres.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_palabraOpcionTres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_palabraOpcionTres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel_palabraOpcionTres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_palabraOpcionTres.setOpaque(true);
        jPanel1.add(jLabel_palabraOpcionTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 350, 220, 70));

        jButton1_Cambiar_oracion.setBackground(new java.awt.Color(51, 51, 255));
        jButton1_Cambiar_oracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Cambiar1.png"))); // NOI18N
        jButton1_Cambiar_oracion.setText("Cambiar Palabra");
        jButton1_Cambiar_oracion.setBorderPainted(false);
        jButton1_Cambiar_oracion.setContentAreaFilled(false);
        jButton1_Cambiar_oracion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Cambiar3.png"))); // NOI18N
        jButton1_Cambiar_oracion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Cambiar2.png"))); // NOI18N
        jPanel1.add(jButton1_Cambiar_oracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 210, 90));

        jButton1_Uno.setText("opcionUno");
        jPanel1.add(jButton1_Uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, -1));

        jButton3_Dos.setText("opcionDos");
        jPanel1.add(jButton3_Dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        jButton3_Tres.setText("opcionTres");
        jPanel1.add(jButton3_Tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 440, -1, -1));

        jLabel3_oracion.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel3_oracion.setForeground(new java.awt.Color(0, 51, 255));
        jPanel1.add(jLabel3_oracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 370, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actividad_5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Cambiar_oracion;
    private javax.swing.JButton jButton1_Salir_act_5;
    private javax.swing.JButton jButton1_Uno;
    private javax.swing.JButton jButton1_Vericicar_oracion;
    private javax.swing.JButton jButton3_Dos;
    private javax.swing.JButton jButton3_Tres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3_oracion;
    private javax.swing.JLabel jLabel_opcionUno;
    private javax.swing.JLabel jLabel_palabraOpcionDos;
    private javax.swing.JLabel jLabel_palabraOpcionTres;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
