/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;


import com.formdev.flatlaf.FlatLightLaf;
import controlador.ControlActividad2;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;

/**
 *
 * @author almen
 */
public class Actividad_2 extends javax.swing.JFrame {
   
    /**
     * Creates new form CompletarPalabras
     */
   ControlActividad2 objControl5;
    public Actividad_2() {
        initComponents();
        this.setLocationRelativeTo(null);
        objControl5= new ControlActividad2(this);      
        initStyles();
    }
    private void initStyles(){
        jButton1_Cambiar_Palabra.putClientProperty( "JButton.buttonType", "roundRect" );
        jButton1_Vericicar_respuesta.putClientProperty( "JButton.buttonType", "roundRect" );
        jButton1_Salir_act_5.putClientProperty( "JButton.buttonType", "roundRect" );
    }

    public JLabel getjLabel_IMAGEN() {
        return jLabel_IMAGEN;
    }

    public JButton getjButton1_instrucciones() {
        return jButton1_instrucciones;
    }
    
    public JButton getjButton1_Salir_act_5() {
        return jButton1_Salir_act_5;
    }

    public JButton getjButton1_Vericicar_respuesta() {
        return jButton1_Vericicar_respuesta;
    }

    public JButton getjButton1_Cambiar_Palabra() {
        return jButton1_Cambiar_Palabra;
    }
    
    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public JLabel getjLabel_destino2() {
        return jLabel_destino2;
    }

    public JLabel getjLabel_destino3() {
        return jLabel_destino3;
    }

    public JLabel getjLabel_destino4() {
        return jLabel_destino4;
    }

    public JLabel getjLabel_destino5() {
        return jLabel_destino5;
    }

    public JLabel getjLabel_destino6() {
        return jLabel_destino6;
    }

    public JLabel getjLabel_detino1() {
        return jLabel_detino1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JButton getjButton1_Repetir_PalabraAudio() {
        return jButton1_Repetir_PalabraAudio;
    }

    public JLabel getCorazon1() {
        return corazon1;
    }

    public JLabel getCorazon2() {
        return corazon2;
    }

    public JLabel getCorazon3() {
        return corazon3;
    }

    public JLabel getCorazon4() {
        return corazon4;
    }

    public JLabel getCorazon5() {
        return corazon5;
    }
    
    

  
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1_Salir_act_5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1_Vericicar_respuesta = new javax.swing.JButton();
        jLabel_detino1 = new javax.swing.JLabel();
        jLabel_destino2 = new javax.swing.JLabel();
        jLabel_destino3 = new javax.swing.JLabel();
        jLabel_destino4 = new javax.swing.JLabel();
        jLabel_destino5 = new javax.swing.JLabel();
        jLabel_destino6 = new javax.swing.JLabel();
        jButton1_Cambiar_Palabra = new javax.swing.JButton();
        jButton1_instrucciones = new javax.swing.JButton();
        jButton1_Repetir_PalabraAudio = new javax.swing.JButton();
        jLabel_IMAGEN = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        corazon1 = new javax.swing.JLabel();
        corazon2 = new javax.swing.JLabel();
        corazon3 = new javax.swing.JLabel();
        corazon4 = new javax.swing.JLabel();
        corazon5 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(82, 160, 254));
        jPanel1.setMinimumSize(new java.awt.Dimension(1203, 630));
        jPanel1.setPreferredSize(new java.awt.Dimension(1203, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1_Salir_act_5.setBackground(new java.awt.Color(153, 51, 255));
        jButton1_Salir_act_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/salirrr.png"))); // NOI18N
        jButton1_Salir_act_5.setBorderPainted(false);
        jButton1_Salir_act_5.setContentAreaFilled(false);
        jButton1_Salir_act_5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1_Salir_act_5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Frame 106.png"))); // NOI18N
        jButton1_Salir_act_5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Frame 104.png"))); // NOI18N
        jPanel1.add(jButton1_Salir_act_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 255, 51));
        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ordena las palabras");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 480, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 80, 128));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 80, 128));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 80, 128));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 80, 128));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, 80, 128));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 160, 80, 128));

        jButton1_Vericicar_respuesta.setBackground(new java.awt.Color(51, 51, 255));
        jButton1_Vericicar_respuesta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/BOTTONCHECK.png"))); // NOI18N
        jButton1_Vericicar_respuesta.setToolTipText("");
        jButton1_Vericicar_respuesta.setBorderPainted(false);
        jButton1_Vericicar_respuesta.setContentAreaFilled(false);
        jButton1_Vericicar_respuesta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_Vericicar_respuesta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/BOTTONCHECKPRESSED.png"))); // NOI18N
        jPanel1.add(jButton1_Vericicar_respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 210, 120));

        jLabel_detino1.setBackground(new java.awt.Color(94, 126, 255));
        jLabel_detino1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_detino1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel_detino1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel_detino1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_detino1.setOpaque(true);
        jPanel1.add(jLabel_detino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 90, 128));

        jLabel_destino2.setBackground(new java.awt.Color(94, 126, 255));
        jLabel_destino2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel_destino2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_destino2.setOpaque(true);
        jPanel1.add(jLabel_destino2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 90, 128));

        jLabel_destino3.setBackground(new java.awt.Color(94, 126, 255));
        jLabel_destino3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_destino3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel_destino3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_destino3.setOpaque(true);
        jPanel1.add(jLabel_destino3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 90, 128));

        jLabel_destino4.setBackground(new java.awt.Color(94, 126, 255));
        jLabel_destino4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel_destino4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_destino4.setOpaque(true);
        jPanel1.add(jLabel_destino4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, 90, 128));

        jLabel_destino5.setBackground(new java.awt.Color(94, 126, 255));
        jLabel_destino5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel_destino5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_destino5.setOpaque(true);
        jPanel1.add(jLabel_destino5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 320, 90, 128));

        jLabel_destino6.setBackground(new java.awt.Color(94, 126, 255));
        jLabel_destino6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel_destino6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_destino6.setOpaque(true);
        jPanel1.add(jLabel_destino6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 320, 90, 128));

        jButton1_Cambiar_Palabra.setBackground(new java.awt.Color(51, 51, 255));
        jButton1_Cambiar_Palabra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/BOTONNEXT.png"))); // NOI18N
        jButton1_Cambiar_Palabra.setBorderPainted(false);
        jButton1_Cambiar_Palabra.setContentAreaFilled(false);
        jButton1_Cambiar_Palabra.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/BOTTONNEXTPRESSED.png"))); // NOI18N
        jPanel1.add(jButton1_Cambiar_Palabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, 170, 110));

        jButton1_instrucciones.setBackground(new java.awt.Color(153, 153, 255));
        jButton1_instrucciones.setBorderPainted(false);
        jButton1_instrucciones.setContentAreaFilled(false);
        jPanel1.add(jButton1_instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 90, 40));

        jButton1_Repetir_PalabraAudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/ESCUCHA.png"))); // NOI18N
        jButton1_Repetir_PalabraAudio.setBorderPainted(false);
        jButton1_Repetir_PalabraAudio.setContentAreaFilled(false);
        jButton1_Repetir_PalabraAudio.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/ESCUCHAPRESSED.png"))); // NOI18N
        jButton1_Repetir_PalabraAudio.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/deshacer.png"))); // NOI18N
        jPanel1.add(jButton1_Repetir_PalabraAudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, 70));

        jLabel_IMAGEN.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel_IMAGEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 270, 290));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/PANEL21.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/PANEL_IMAGENm1.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 380, 380));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/TITULO.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));
        jPanel1.add(corazon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 50, 40));
        jPanel1.add(corazon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 50, 40));
        jPanel1.add(corazon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 50, 40));
        jPanel1.add(corazon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 50, 40));
        jPanel1.add(corazon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actividad_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel corazon1;
    private javax.swing.JLabel corazon2;
    private javax.swing.JLabel corazon3;
    private javax.swing.JLabel corazon4;
    private javax.swing.JLabel corazon5;
    private javax.swing.JButton jButton1_Cambiar_Palabra;
    private javax.swing.JButton jButton1_Repetir_PalabraAudio;
    private javax.swing.JButton jButton1_Salir_act_5;
    private javax.swing.JButton jButton1_Vericicar_respuesta;
    private javax.swing.JButton jButton1_instrucciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_IMAGEN;
    private javax.swing.JLabel jLabel_destino2;
    private javax.swing.JLabel jLabel_destino3;
    private javax.swing.JLabel jLabel_destino4;
    private javax.swing.JLabel jLabel_destino5;
    private javax.swing.JLabel jLabel_destino6;
    private javax.swing.JLabel jLabel_detino1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
