/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import controlador.ControlMenu;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author juare
 */
public class Menu_Actividades extends javax.swing.JPanel {

    /**
     * Creates new form Menu_Actividades
     */
    private ControlMenu control;

    public Menu_Actividades(ControlMenu control) {
    this.control = control;
    initComponents();
    
    }
   
   
    public JButton getjButton_Actividad1() {
        return jButton_Actividad1;
    }

    public JButton getjButton_Actividad2() {
        return jButton_Actividad2;
    }

    public JButton getjButton_Actividad3() {
        return jButton_Actividad3;
    }

    public JButton getjButton_Actividad4() {
        return jButton_Actividad4;
    }

    public JButton getjButton_Actividad5() {
        return jButton_Actividad5;
    }

    public JButton getjButton_Actividad6() {
        return jButton_Actividad6;
    }

    public JPanel getjPanel_Menu() {
        return jPanel_Menu;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Menu = new javax.swing.JPanel();
        jButton_Actividad2 = new javax.swing.JButton();
        jButton_Actividad3 = new javax.swing.JButton();
        jButton_Actividad4 = new javax.swing.JButton();
        jButton_Actividad5 = new javax.swing.JButton();
        jButton_Actividad6 = new javax.swing.JButton();
        jButton_Actividad1 = new javax.swing.JButton();

        jPanel_Menu.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Actividad2.setBackground(new java.awt.Color(83, 167, 216));
        jButton_Actividad2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Actividad2.png"))); // NOI18N
        jButton_Actividad2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton_Actividad2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Menu.add(jButton_Actividad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 260, 250));

        jButton_Actividad3.setBackground(new java.awt.Color(83, 167, 216));
        jButton_Actividad3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Actividad3.png"))); // NOI18N
        jButton_Actividad3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton_Actividad3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Menu.add(jButton_Actividad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 260, 250));

        jButton_Actividad4.setBackground(new java.awt.Color(83, 167, 216));
        jButton_Actividad4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Frame 12.png"))); // NOI18N
        jButton_Actividad4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton_Actividad4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Menu.add(jButton_Actividad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 260, 250));

        jButton_Actividad5.setBackground(new java.awt.Color(83, 167, 216));
        jButton_Actividad5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Frame 12.png"))); // NOI18N
        jButton_Actividad5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton_Actividad5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Menu.add(jButton_Actividad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 260, 250));

        jButton_Actividad6.setBackground(new java.awt.Color(83, 167, 216));
        jButton_Actividad6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Frame 12.png"))); // NOI18N
        jButton_Actividad6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton_Actividad6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Menu.add(jButton_Actividad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 260, 250));

        jButton_Actividad1.setBackground(new java.awt.Color(83, 167, 216));
        jButton_Actividad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Actividad1.png"))); // NOI18N
        jButton_Actividad1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton_Actividad1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Actividad1.setIconTextGap(1);
        jPanel_Menu.add(jButton_Actividad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 260, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Actividad1;
    private javax.swing.JButton jButton_Actividad2;
    private javax.swing.JButton jButton_Actividad3;
    private javax.swing.JButton jButton_Actividad4;
    private javax.swing.JButton jButton_Actividad5;
    private javax.swing.JButton jButton_Actividad6;
    private javax.swing.JPanel jPanel_Menu;
    // End of variables declaration//GEN-END:variables
}
