/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import com.formdev.flatlaf.FlatLightLaf;
import controlador.ControlMenu;
import javax.swing.JButton;

/**
 *
 * @author juare
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    ControlMenu objControlMenu;
    public Menu() {
        initComponents();
        setSize(1213, 700); 
        setDefaultCloseOperation(Menu.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); 
        setVisible(true);
        objControlMenu = new ControlMenu(this);
    }

    public JButton getjButton_Actividad1() {
        return jButton_Actividad1;
    }

    public JButton getjButton_Actividad2() {
        return jButton_Actividad2;
    }

    public JButton getjButton_Actividad3() {
        return jButton_Actividad3;
    }

    public JButton getjButton_Actividad4() {
        return jButton_Actividad4;
    }

    public JButton getjButton_Actividad5() {
        return jButton_Actividad5;
    }

    public JButton getjButton_Actividad6() {
        return jButton_Actividad6;
    }

    public JButton getjButton5_Salir_Menu() {
        return jButton5_Salir_Menu;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Opciones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5_Salir_Menu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel_Menu = new javax.swing.JPanel();
        jButton_Actividad2 = new javax.swing.JButton();
        jButton_Actividad3 = new javax.swing.JButton();
        jButton_Actividad4 = new javax.swing.JButton();
        jButton_Actividad5 = new javax.swing.JButton();
        jButton_Actividad6 = new javax.swing.JButton();
        jButton_Actividad1 = new javax.swing.JButton();
        jPanel_Mensages = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Opciones.setBackground(new java.awt.Color(102, 51, 255));
        jPanel_Opciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 0, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("INICIO");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton1.setIconTextGap(5);
        jButton1.setMargin(new java.awt.Insets(10, 14, 3, 14));
        jButton1.setOpaque(true);
        jPanel_Opciones.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 50));

        jButton2.setBackground(new java.awt.Color(102, 0, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("AJUSTES");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setIconTextGap(10);
        jButton2.setOpaque(true);
        jPanel_Opciones.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 50));

        jButton3.setBackground(new java.awt.Color(102, 0, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("AYUDA");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Opciones.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 50));

        jButton4.setBackground(new java.awt.Color(102, 0, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("PROGRESO");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Opciones.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 230, 50));

        jButton5_Salir_Menu.setBackground(new java.awt.Color(51, 51, 255));
        jButton5_Salir_Menu.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jButton5_Salir_Menu.setForeground(new java.awt.Color(0, 0, 0));
        jButton5_Salir_Menu.setText("SALIR");
        jButton5_Salir_Menu.setBorder(null);
        jButton5_Salir_Menu.setBorderPainted(false);
        jButton5_Salir_Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Opciones.add(jButton5_Salir_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 587, 230, 60));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel_Opciones.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 200, 10));

        getContentPane().add(jPanel_Opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 690));

        jPanel_Menu.setBackground(new java.awt.Color(153, 153, 255));
        jPanel_Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Actividad2.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Actividad2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/buscando 2.png"))); // NOI18N
        jButton_Actividad2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton_Actividad2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Menu.add(jButton_Actividad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 200, 210));

        jButton_Actividad3.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Actividad3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/a-b-c 1.png"))); // NOI18N
        jButton_Actividad3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton_Actividad3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Menu.add(jButton_Actividad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 200, 210));

        jButton_Actividad4.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Actividad4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image-removebg-preview (15) 1.png"))); // NOI18N
        jButton_Actividad4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton_Actividad4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Menu.add(jButton_Actividad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 200, 210));

        jButton_Actividad5.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Actividad5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image-removebg-preview (16) 1.png"))); // NOI18N
        jButton_Actividad5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton_Actividad5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Menu.add(jButton_Actividad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 200, 210));

        jButton_Actividad6.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Actividad6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton_Actividad6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Menu.add(jButton_Actividad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 200, 210));

        jButton_Actividad1.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Actividad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image-removebg-preview (14) 1.png"))); // NOI18N
        jButton_Actividad1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton_Actividad1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel_Menu.add(jButton_Actividad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 200, 210));

        getContentPane().add(jPanel_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 990, 610));

        jPanel_Mensages.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout jPanel_MensagesLayout = new javax.swing.GroupLayout(jPanel_Mensages);
        jPanel_Mensages.setLayout(jPanel_MensagesLayout);
        jPanel_MensagesLayout.setHorizontalGroup(
            jPanel_MensagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        jPanel_MensagesLayout.setVerticalGroup(
            jPanel_MensagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel_Mensages, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 990, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        
        FlatLightLaf.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5_Salir_Menu;
    private javax.swing.JButton jButton_Actividad1;
    private javax.swing.JButton jButton_Actividad2;
    private javax.swing.JButton jButton_Actividad3;
    private javax.swing.JButton jButton_Actividad4;
    private javax.swing.JButton jButton_Actividad5;
    private javax.swing.JButton jButton_Actividad6;
    private javax.swing.JPanel jPanel_Mensages;
    private javax.swing.JPanel jPanel_Menu;
    private javax.swing.JPanel jPanel_Opciones;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
