/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import controlador.ControlMenu;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author juare
 */
public class Menu_Actividades extends javax.swing.JPanel {

    /**
     * Creates new form Menu_Actividades
     */
    private ControlMenu control;

    public Menu_Actividades(ControlMenu control) {
    this.control = control;
    initComponents();
    
    }
   
   
    public JButton getjButton_Actividad1() {
        return jButton_Actividad1;
    }

    public JButton getjButton_Actividad2() {
        return jButton_Actividad2;
    }

    public JButton getjButton_Actividad3() {
        return jButton_Actividad3;
    }

    public JButton getjButton_Actividad4() {
        return jButton_Actividad4;
    }

    public JButton getjButton_Actividad5() {
        return jButton_Actividad5;
    }

    public JButton getjButton_Actividad6() {
        return jButton_Actividad6;
    }

    public JPanel getjPanel_Menu() {
        return jPanel_Menu;
    }

    public JLabel getjLabel_Acti1() {
        return jLabel_Acti1;
    }

    public JLabel getjLabel_Acti2() {
        return jLabel_Acti2;
    }

    public JLabel getjLabel_Acti3() {
        return jLabel_Acti3;
    }

    public JLabel getjLabel_Acti4() {
        return jLabel_Acti4;
    }

    public JLabel getjLabel_Acti5() {
        return jLabel_Acti5;
    }

    public JLabel getjLabel_Acti6() {
        return jLabel_Acti6;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Menu = new javax.swing.JPanel();
        jButton_Actividad2 = new javax.swing.JButton();
        jButton_Actividad3 = new javax.swing.JButton();
        jButton_Actividad4 = new javax.swing.JButton();
        jButton_Actividad5 = new javax.swing.JButton();
        jButton_Actividad6 = new javax.swing.JButton();
        jButton_Actividad1 = new javax.swing.JButton();
        jLabel_Acti1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Acti2 = new javax.swing.JLabel();
        jLabel_Acti3 = new javax.swing.JLabel();
        jLabel_Acti4 = new javax.swing.JLabel();
        jLabel_Acti5 = new javax.swing.JLabel();
        jLabel_Acti6 = new javax.swing.JLabel();

        jPanel_Menu.setBackground(new java.awt.Color(232, 232, 232));
        jPanel_Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Actividad2.setBackground(new java.awt.Color(83, 167, 216));
        jButton_Actividad2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton.png"))); // NOI18N
        jButton_Actividad2.setBorder(null);
        jButton_Actividad2.setBorderPainted(false);
        jButton_Actividad2.setContentAreaFilled(false);
        jButton_Actividad2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Actividad2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/button_pressed.png"))); // NOI18N
        jButton_Actividad2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/button_mause.png"))); // NOI18N
        jButton_Actividad2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/button_mause.png"))); // NOI18N
        jPanel_Menu.add(jButton_Actividad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 190, 50));

        jButton_Actividad3.setBackground(new java.awt.Color(83, 167, 216));
        jButton_Actividad3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton.png"))); // NOI18N
        jButton_Actividad3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton_Actividad3.setBorderPainted(false);
        jButton_Actividad3.setContentAreaFilled(false);
        jButton_Actividad3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Actividad3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/button_pressed.png"))); // NOI18N
        jButton_Actividad3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/button_mause.png"))); // NOI18N
        jPanel_Menu.add(jButton_Actividad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 190, 60));

        jButton_Actividad4.setBackground(new java.awt.Color(83, 167, 216));
        jButton_Actividad4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton.png"))); // NOI18N
        jButton_Actividad4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton_Actividad4.setBorderPainted(false);
        jButton_Actividad4.setContentAreaFilled(false);
        jButton_Actividad4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Actividad4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/button_pressed.png"))); // NOI18N
        jButton_Actividad4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/button_mause.png"))); // NOI18N
        jPanel_Menu.add(jButton_Actividad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 190, 60));

        jButton_Actividad5.setBackground(new java.awt.Color(83, 167, 216));
        jButton_Actividad5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton.png"))); // NOI18N
        jButton_Actividad5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton_Actividad5.setBorderPainted(false);
        jButton_Actividad5.setContentAreaFilled(false);
        jButton_Actividad5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Actividad5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/button_pressed.png"))); // NOI18N
        jButton_Actividad5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/button_mause.png"))); // NOI18N
        jPanel_Menu.add(jButton_Actividad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 190, 70));

        jButton_Actividad6.setBackground(new java.awt.Color(83, 167, 216));
        jButton_Actividad6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton.png"))); // NOI18N
        jButton_Actividad6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton_Actividad6.setBorderPainted(false);
        jButton_Actividad6.setContentAreaFilled(false);
        jButton_Actividad6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Actividad6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/button_pressed.png"))); // NOI18N
        jButton_Actividad6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/button_mause.png"))); // NOI18N
        jPanel_Menu.add(jButton_Actividad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 190, 70));

        jButton_Actividad1.setBackground(new java.awt.Color(83, 167, 216));
        jButton_Actividad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton.png"))); // NOI18N
        jButton_Actividad1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jButton_Actividad1.setBorderPainted(false);
        jButton_Actividad1.setContentAreaFilled(false);
        jButton_Actividad1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Actividad1.setIconTextGap(1);
        jButton_Actividad1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/button_pressed.png"))); // NOI18N
        jButton_Actividad1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/button_mause.png"))); // NOI18N
        jButton_Actividad1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/button_mause.png"))); // NOI18N
        jPanel_Menu.add(jButton_Actividad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 190, 60));

        jLabel_Acti1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/modulo1.png"))); // NOI18N
        jLabel_Acti1.setText("jLabel2");
        jPanel_Menu.add(jLabel_Acti1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 290, 280));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Modulos de aprendizaje");
        jPanel_Menu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 190, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Modulo_Aprendizaje.png"))); // NOI18N
        jLabel1.setText("Modulos de aprendizaje");
        jPanel_Menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        jLabel_Acti2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/modulo5.png"))); // NOI18N
        jPanel_Menu.add(jLabel_Acti2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 290, 280));

        jLabel_Acti3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/modulo3.png"))); // NOI18N
        jLabel_Acti3.setText("jLabel4");
        jPanel_Menu.add(jLabel_Acti3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 290, 270));

        jLabel_Acti4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/modulo4.png"))); // NOI18N
        jLabel_Acti4.setText("jLabel5");
        jPanel_Menu.add(jLabel_Acti4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 290, 280));

        jLabel_Acti5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/modulo2.png"))); // NOI18N
        jLabel_Acti5.setText("jLabel6");
        jPanel_Menu.add(jLabel_Acti5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 290, 270));

        jLabel_Acti6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/modulo6.png"))); // NOI18N
        jLabel_Acti6.setText("jLabel7");
        jPanel_Menu.add(jLabel_Acti6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 290, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Actividad1;
    private javax.swing.JButton jButton_Actividad2;
    private javax.swing.JButton jButton_Actividad3;
    private javax.swing.JButton jButton_Actividad4;
    private javax.swing.JButton jButton_Actividad5;
    private javax.swing.JButton jButton_Actividad6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Acti1;
    private javax.swing.JLabel jLabel_Acti2;
    private javax.swing.JLabel jLabel_Acti3;
    private javax.swing.JLabel jLabel_Acti4;
    private javax.swing.JLabel jLabel_Acti5;
    private javax.swing.JLabel jLabel_Acti6;
    private javax.swing.JPanel jPanel_Menu;
    // End of variables declaration//GEN-END:variables
}
