/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.ControlRegistroPatron;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToggleButton;

/**
 *
 * @author juare
 */
public class Registro_patron extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    ControlRegistroPatron cR;
    
    public Registro_patron() {
        initComponents();
        this.setLocationRelativeTo(null);
        cR= new ControlRegistroPatron(this);
    }

    public JButton getjButton10_intruccion() {
        return jButton10_intruccion;
    }

    public JPanel getjPanel_panelDerecha() {
        return jPanel_panelDerecha;
    }
    
    
    public JPanel getjPanel_patronR() {
        return jPanel_patronR;
    }
    
    public JButton getjButton1_guardar() {
        return jButton1_guardar;
    }

    public JButton getjButton1_Salir1() {
        return jButton1_Salir1;
    }

    public JButton getjButton_iconoregistro1() {
        return jButton_iconoregistro1;
    }

    public JButton getjButton_iconoregistro2() {
        return jButton_iconoregistro2;
    }

    public JButton getjButton_iconoregistro3() {
        return jButton_iconoregistro3;
    }

    public JButton getjButton_iconoregistro4() {
        return jButton_iconoregistro4;
    }

    public JButton getjButton_iconoregistro5() {
        return jButton_iconoregistro5;
    }

    public JButton getjButton_iconoregistro6() {
        return jButton_iconoregistro6;
    }

    public JButton getjButton_iconoregistro7() {
        return jButton_iconoregistro7;
    }

    public JButton getjButton_iconoregistro8() {
        return jButton_iconoregistro8;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }


    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JPanel getjPanel_Registrar() {
        return jPanel_Registrar;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Registrar = new javax.swing.JPanel();
        jButton_iconoregistro8 = new javax.swing.JButton();
        jButton_iconoregistro1 = new javax.swing.JButton();
        jButton_iconoregistro2 = new javax.swing.JButton();
        jButton_iconoregistro3 = new javax.swing.JButton();
        jButton_iconoregistro4 = new javax.swing.JButton();
        jButton_iconoregistro5 = new javax.swing.JButton();
        jButton_iconoregistro6 = new javax.swing.JButton();
        jButton_iconoregistro7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1_guardar = new javax.swing.JButton();
        jButton1_Salir1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel_patronR = new utils.PanelPatronConLineas();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton10_intruccion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel_panelDerecha = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Registrar.setBackground(new java.awt.Color(89, 0, 253));
        jPanel_Registrar.setForeground(new java.awt.Color(51, 51, 255));
        jPanel_Registrar.setMinimumSize(new java.awt.Dimension(1000, 610));
        jPanel_Registrar.setPreferredSize(new java.awt.Dimension(1000, 610));
        jPanel_Registrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_iconoregistro8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/perfil_hombre3.png"))); // NOI18N
        jButton_iconoregistro8.setBorderPainted(false);
        jButton_iconoregistro8.setContentAreaFilled(false);
        jPanel_Registrar.add(jButton_iconoregistro8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 70, 70));

        jButton_iconoregistro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icno_niña.png"))); // NOI18N
        jButton_iconoregistro1.setBorderPainted(false);
        jButton_iconoregistro1.setContentAreaFilled(false);
        jButton_iconoregistro1.setName(""); // NOI18N
        jPanel_Registrar.add(jButton_iconoregistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 70, 70));

        jButton_iconoregistro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icono_hombre 2.png"))); // NOI18N
        jButton_iconoregistro2.setBorderPainted(false);
        jButton_iconoregistro2.setContentAreaFilled(false);
        jPanel_Registrar.add(jButton_iconoregistro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 70, 70));

        jButton_iconoregistro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icono_hombre.png"))); // NOI18N
        jButton_iconoregistro3.setBorderPainted(false);
        jButton_iconoregistro3.setContentAreaFilled(false);
        jPanel_Registrar.add(jButton_iconoregistro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 70, 70));

        jButton_iconoregistro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icono_mujer1.png"))); // NOI18N
        jButton_iconoregistro4.setBorderPainted(false);
        jButton_iconoregistro4.setContentAreaFilled(false);
        jPanel_Registrar.add(jButton_iconoregistro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 70, 70));

        jButton_iconoregistro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icono_mujer2.png"))); // NOI18N
        jButton_iconoregistro5.setBorderPainted(false);
        jButton_iconoregistro5.setContentAreaFilled(false);
        jPanel_Registrar.add(jButton_iconoregistro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 70, 70));

        jButton_iconoregistro6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icono_mujer3.png"))); // NOI18N
        jButton_iconoregistro6.setBorderPainted(false);
        jButton_iconoregistro6.setContentAreaFilled(false);
        jPanel_Registrar.add(jButton_iconoregistro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 70, 70));

        jButton_iconoregistro7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icono_señor.png"))); // NOI18N
        jButton_iconoregistro7.setBorderPainted(false);
        jButton_iconoregistro7.setContentAreaFilled(false);
        jPanel_Registrar.add(jButton_iconoregistro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 130, 70, 70));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Elige tu perfil");
        jPanel_Registrar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Contraseña");
        jPanel_Registrar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jButton1_guardar.setBackground(new java.awt.Color(0, 0, 255));
        jButton1_guardar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1_guardar.setText("Guardar");
        jButton1_guardar.setName("guardar"); // NOI18N
        jButton1_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_guardarActionPerformed(evt);
            }
        });
        jPanel_Registrar.add(jButton1_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 178, -1));

        jButton1_Salir1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1_Salir1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1_Salir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/salirexit.png"))); // NOI18N
        jButton1_Salir1.setText("Salir");
        jButton1_Salir1.setName("borrar"); // NOI18N
        jButton1_Salir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Salir1ActionPerformed(evt);
            }
        });
        jPanel_Registrar.add(jButton1_Salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 178, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel_Registrar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, 0, 260, 270));

        jPanel_patronR.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_patronR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton1.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel_patronR.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 70));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton1.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel_patronR.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 70, 70));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton1.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton2.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel_patronR.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 70, 70));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton1.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton2.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel_patronR.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 70));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton1.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton2.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel_patronR.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 70, 70));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton1.png"))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton2.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel_patronR.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 70, 70));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton1.png"))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton2.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel_patronR.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, 70));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton1.png"))); // NOI18N
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton2.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel_patronR.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 70, 70));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton1.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/boton2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel_patronR.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 70, 70));

        jPanel_Registrar.add(jPanel_patronR, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 360, 250));

        jButton10_intruccion.setText("instruccion");
        jButton10_intruccion.setBorderPainted(false);
        jButton10_intruccion.setContentAreaFilled(false);
        jButton10_intruccion.setName("instruccion"); // NOI18N
        jPanel_Registrar.add(jButton10_intruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 50, 50));

        getContentPane().add(jPanel_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 480, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 610));

        jPanel_panelDerecha.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_panelDerecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel_panelDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 320, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_guardarActionPerformed

    private void jButton1_Salir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Salir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1_Salir1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_patron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_patron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_patron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_patron.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_patron().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10_intruccion;
    private javax.swing.JButton jButton1_Salir1;
    private javax.swing.JButton jButton1_guardar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton_iconoregistro1;
    private javax.swing.JButton jButton_iconoregistro2;
    private javax.swing.JButton jButton_iconoregistro3;
    private javax.swing.JButton jButton_iconoregistro4;
    private javax.swing.JButton jButton_iconoregistro5;
    private javax.swing.JButton jButton_iconoregistro6;
    private javax.swing.JButton jButton_iconoregistro7;
    private javax.swing.JButton jButton_iconoregistro8;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_Registrar;
    private javax.swing.JPanel jPanel_panelDerecha;
    private utils.PanelPatronConLineas jPanel_patronR;
    // End of variables declaration//GEN-END:variables
}
