/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.ControlRePa;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.*;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.dnd.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
/**
 *
 * @author juare
 */
public class RelacionarPalabras extends javax.swing.JFrame {

    /**
     * Creates new form RelacionarPalabras
     */
    
    ControlRePa control;
    public RelacionarPalabras() {
        initComponents();
        control = new ControlRePa(this);
        
    }
    public JLabel getjLabel1_palabra1() {
        return jLabel1_palabra1;
    }

    public void setjLabel1_palabra1(JLabel jLabel1_palabra1) {
        this.jLabel1_palabra1 = jLabel1_palabra1;
    }

    public JLabel getjLabel2_palabra3() {
        return jLabel2_palabra3;
    }

    public void setjLabel2_palabra3(JLabel jLabel2_palabra3) {
        this.jLabel2_palabra3 = jLabel2_palabra3;
    }

    public JLabel getjLabel3_palabra2() {
        return jLabel3_palabra2;
    }

    public void setjLabel3_palabra2(JLabel jLabel3_palabra2) {
        this.jLabel3_palabra2 = jLabel3_palabra2;
    }

    

    public JPanel getjPanel1_obj1() {
        return jPanel1_obj1;
    }

    public void setjPanel1_obj1(JPanel jPanel1_obj1) {
        this.jPanel1_obj1 = jPanel1_obj1;
    }

    public JPanel getjPanel1_obj3() {
        return jPanel1_obj3;
    }

    public void setjPanel1_obj3(JPanel jPanel1_obj3) {
        this.jPanel1_obj3 = jPanel1_obj3;
    }

    public JPanel getjPanel2_obj2() {
        return jPanel2_obj2;
    }

    public void setjPanel2_obj2(JPanel jPanel2_obj2) {
        this.jPanel2_obj2 = jPanel2_obj2;
    }

    public JLabel getJlabel_image1() {
        return jlabel_image1;
    }

    public void setJlabel_image1(JLabel jlabel_image1) {
        this.jlabel_image1 = jlabel_image1;
    }

    public JLabel getJlabel_image2() {
        return jlabel_image2;
    }

    public void setJlabel_image2(JLabel jlabel_image2) {
        this.jlabel_image2 = jlabel_image2;
    }

    public JLabel getJlabel_image3() {
        return jlabel_image3;
    }

    public void setJlabel_image3(JLabel jlabel_image3) {
        this.jlabel_image3 = jlabel_image3;
    }
   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3_fondo = new javax.swing.JPanel();
        jPanel1_obj1 = new javax.swing.JPanel();
        jPanel2_obj2 = new javax.swing.JPanel();
        jPanel1_obj3 = new javax.swing.JPanel();
        jlabel_image1 = new javax.swing.JLabel();
        jlabel_image2 = new javax.swing.JLabel();
        jlabel_image3 = new javax.swing.JLabel();
        jLabel1_palabra1 = new javax.swing.JLabel();
        jLabel2_palabra3 = new javax.swing.JLabel();
        jLabel3_palabra2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1160, 650));

        jPanel3_fondo.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1_obj1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1_obj1Layout = new javax.swing.GroupLayout(jPanel1_obj1);
        jPanel1_obj1.setLayout(jPanel1_obj1Layout);
        jPanel1_obj1Layout.setHorizontalGroup(
            jPanel1_obj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel1_obj1Layout.setVerticalGroup(
            jPanel1_obj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel3_fondo.add(jPanel1_obj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 220, 80));

        jPanel2_obj2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2_obj2Layout = new javax.swing.GroupLayout(jPanel2_obj2);
        jPanel2_obj2.setLayout(jPanel2_obj2Layout);
        jPanel2_obj2Layout.setHorizontalGroup(
            jPanel2_obj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel2_obj2Layout.setVerticalGroup(
            jPanel2_obj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel3_fondo.add(jPanel2_obj2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 220, 80));

        jPanel1_obj3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1_obj3Layout = new javax.swing.GroupLayout(jPanel1_obj3);
        jPanel1_obj3.setLayout(jPanel1_obj3Layout);
        jPanel1_obj3Layout.setHorizontalGroup(
            jPanel1_obj3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel1_obj3Layout.setVerticalGroup(
            jPanel1_obj3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel3_fondo.add(jPanel1_obj3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 220, 80));

        jlabel_image1.setBackground(new java.awt.Color(204, 204, 204));
        jlabel_image1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3_fondo.add(jlabel_image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 130, 110));

        jlabel_image2.setBackground(new java.awt.Color(204, 204, 204));
        jlabel_image2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3_fondo.add(jlabel_image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 130, 110));

        jlabel_image3.setBackground(new java.awt.Color(204, 204, 204));
        jlabel_image3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3_fondo.add(jlabel_image3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 130, 110));

        jLabel1_palabra1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1_palabra1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1_palabra1.setText("brian");
        jLabel1_palabra1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1_palabra1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_palabra1.setOpaque(true);
        jPanel3_fondo.add(jLabel1_palabra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 219, 80));

        jLabel2_palabra3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2_palabra3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3_fondo.add(jLabel2_palabra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 219, 80));

        jLabel3_palabra2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3_palabra2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3_fondo.add(jLabel3_palabra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 219, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3_fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelacionarPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelacionarPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelacionarPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelacionarPalabras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelacionarPalabras().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1_palabra1;
    private javax.swing.JLabel jLabel2_palabra3;
    private javax.swing.JLabel jLabel3_palabra2;
    private javax.swing.JPanel jPanel1_obj1;
    private javax.swing.JPanel jPanel1_obj3;
    private javax.swing.JPanel jPanel2_obj2;
    private javax.swing.JPanel jPanel3_fondo;
    private javax.swing.JLabel jlabel_image1;
    private javax.swing.JLabel jlabel_image2;
    private javax.swing.JLabel jlabel_image3;
    // End of variables declaration//GEN-END:variables
}
