/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

/**
 *
 * @author juare
 */
public class Vocal_A extends javax.swing.JPanel {

    /**
     * Creates new form Abecedario
     */
    public Vocal_A() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_A = new javax.swing.JButton();
        jButton_B = new javax.swing.JButton();
        jButton_C = new javax.swing.JButton();
        jButton_D = new javax.swing.JButton();
        jButton_E = new javax.swing.JButton();
        jButton_F = new javax.swing.JButton();
        jButton_G = new javax.swing.JButton();
        jButton_H = new javax.swing.JButton();
        jButton_I = new javax.swing.JButton();

        setBackground(new java.awt.Color(116, 159, 183));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/vocal_A1.png"))); // NOI18N
        jButton_A.setBorderPainted(false);
        jButton_A.setContentAreaFilled(false);
        jButton_A.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_A.setName("vocala"); // NOI18N
        jButton_A.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/vocal_A2.png"))); // NOI18N
        jButton_A.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/vocal_A3.png"))); // NOI18N
        add(jButton_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 150, 150));

        jButton_B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Abajo1.png"))); // NOI18N
        jButton_B.setBorderPainted(false);
        jButton_B.setContentAreaFilled(false);
        jButton_B.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_B.setName("abajo"); // NOI18N
        jButton_B.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Abajo2.png"))); // NOI18N
        jButton_B.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Abajo3.png"))); // NOI18N
        add(jButton_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, 120));

        jButton_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Aire1.png"))); // NOI18N
        jButton_C.setBorderPainted(false);
        jButton_C.setContentAreaFilled(false);
        jButton_C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_C.setName("aire"); // NOI18N
        jButton_C.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Aire2.png"))); // NOI18N
        jButton_C.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Aire3.png"))); // NOI18N
        add(jButton_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 180, 130));

        jButton_D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Animal1.png"))); // NOI18N
        jButton_D.setBorderPainted(false);
        jButton_D.setContentAreaFilled(false);
        jButton_D.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_D.setName("animal"); // NOI18N
        jButton_D.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Animal2.png"))); // NOI18N
        jButton_D.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Animal3.png"))); // NOI18N
        add(jButton_D, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 170, 120));

        jButton_E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Agua1.png"))); // NOI18N
        jButton_E.setBorderPainted(false);
        jButton_E.setContentAreaFilled(false);
        jButton_E.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_E.setName("agua"); // NOI18N
        jButton_E.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Agua2.png"))); // NOI18N
        jButton_E.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Agua3.png"))); // NOI18N
        add(jButton_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 190, 120));

        jButton_F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Arbol1.png"))); // NOI18N
        jButton_F.setBorderPainted(false);
        jButton_F.setContentAreaFilled(false);
        jButton_F.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_F.setName("arbol"); // NOI18N
        jButton_F.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Arbol2.png"))); // NOI18N
        jButton_F.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Arbol3.png"))); // NOI18N
        add(jButton_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 180, 120));

        jButton_G.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Camino1.png"))); // NOI18N
        jButton_G.setBorderPainted(false);
        jButton_G.setContentAreaFilled(false);
        jButton_G.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_G.setName("camino"); // NOI18N
        jButton_G.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Camino2.png"))); // NOI18N
        jButton_G.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Camino3.png"))); // NOI18N
        add(jButton_G, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 180, 110));

        jButton_H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Amigo1.png"))); // NOI18N
        jButton_H.setBorderPainted(false);
        jButton_H.setContentAreaFilled(false);
        jButton_H.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_H.setName("amigo"); // NOI18N
        jButton_H.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Amigo2.png"))); // NOI18N
        jButton_H.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Amigo3.png"))); // NOI18N
        add(jButton_H, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 160, 120));

        jButton_I.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Alma1.png"))); // NOI18N
        jButton_I.setBorderPainted(false);
        jButton_I.setContentAreaFilled(false);
        jButton_I.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_I.setName("alma"); // NOI18N
        jButton_I.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Alma2.png"))); // NOI18N
        jButton_I.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/vocales/Alma3.png"))); // NOI18N
        add(jButton_I, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 160, 100));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_A;
    private javax.swing.JButton jButton_B;
    private javax.swing.JButton jButton_C;
    private javax.swing.JButton jButton_D;
    private javax.swing.JButton jButton_E;
    private javax.swing.JButton jButton_F;
    private javax.swing.JButton jButton_G;
    private javax.swing.JButton jButton_H;
    private javax.swing.JButton jButton_I;
    // End of variables declaration//GEN-END:variables
}
